#!/bin/bash

# Path to the WAR file generated by Jenkins
WAR_FILE="./target/02-RestAPI-PaytmApp-0.0.1-SNAPSHOT.war"

# Path to Tomcat's webapps directory
WEBAPPS_DIR="/opt/tomcat/webapps"

# Extract context path from WAR file name
CONTEXT_PATH=$(basename "$WAR_FILE" .war)

# Transfer WAR file to Tomcat's webapps directory
cp "$WAR_FILE" "$WEBAPPS_DIR/$CONTEXT_PATH.war"

# Restart Tomcat to deploy the application
sudo systemctl restart tomcat

# Verify deployment status
echo "Deployment to production complete. Verifying application status..."
sleep 10 # Wait for Tomcat to restart
curl -sSf "http://localhost:7070/$CONTEXT_PATH" >/dev/null && echo "Application deployed successfully." || echo "Deployment failed."
