#!/bin/bash

# Path to the WAR file generated by Jenkins
WAR_FILE="/opt/tomcat/webapps/02-RestAPI-PaytmApp-0.0.1-SNAPSHOT.war"

# Path to Tomcat's webapps directory
WEBAPPS_DIR="/opt/tomcat/webapps/"

# Copy WAR file to Tomcat's webapps directory
cp "$WAR_FILE" "$WEBAPPS_DIR"

# Verify deployment status
echo "Deployment to production complete. Verifying application status..."
sleep 10 # Wait for Tomcat to deploy the application
curl -sSf "http://localhost:7070/02-RestAPI-PaytmApp-0.0.1-SNAPSHOT" >/dev/null && echo "Application deployed successfully." || echo "Deployment failed."
